### ISSUE TITLE
[LOGIN] - Cadastro próprio para empresas

### ISSUE THREAD

**Issue by Tiago-Marques** [Tiago-Marques/OngsDonate#2]
A Dri comentou que muitos usuários podem querer fazer as doações usando o nome de suas empresas (padaria, comercio, etc) e normalmente nesses acessos não se tem um perfil facebook ou gmail.

**Comment by Tiago-Marques** [comment]
Ficou definido que terá usuário local.

**Comment by feraline** [comment]
Isso responde também a pergunta que está na ata?

**Comment by Tiago-Marques** [comment]
@feraline qual pergunta e qual ata ?
