### ISSUE TITLE
[MENU] - Botão sair/logout 

### ISSUE THREAD

**Issue by Tiago-Marques** [Tiago-Marques/OngsDonate#5]
Precisamos dele?

**Comment by Tiago-Marques** [comment]
Vai precisar ! (:

**Comment by feraline** [comment]
@Tiago-Marques, tem uma task criada para essa questão? Para o pessoal não esquecer de incluir o botão?

**Comment by Tiago-Marques** [comment]
@feraline Criado ( #11 ) !
